version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/todo-app

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
