version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/project-api
    permissions:
    - object: /home/ec2-user/project-api
      owner: ec2-user
      group: ec2-user
      mode: 755

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
