version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo "CodeBuild ENV Variables => APPNAME=$APPNAME , ENVIRONMENT=$ENVIRONMENT"
      - echo Fetching environment variables from SSM Parameter Store...
      - DATABASE_URL=$(aws ssm get-parameter --name "/$APPNAME/$ENVIRONMENT/DATABASE_URL" --region $AWS_DEFAULT_REGION --with-decryption --query "Parameter.Value" --output text)
      - echo "DATABASE_URL = $DATABASE_URL"
      - echo Running Prisma generate...
      - npx prisma generate
  build:
    commands:
      - echo Compiling TypeScript...
      - npm run build
  post_build:
    commands:
      - echo Preparing artifact for deployment...
      - echo "Creating envfile with ENVIRONMENT=$ENVIRONMENT"
      - echo "DATABASE_URL=$DATABASE_URL" > .env
      - mkdir -p deploy
      - cp -r dist package*.json appspec.yml scripts prisma .env deploy/
artifacts:
  files:
    - 'deploy/**/*'